spring:
  application:
    name: pawnshop-service-gateway

  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: oauth2-service
          uri: http://www.ckh.com:8101
          predicates:
            - Path=/oauth/**
        - id: user-service
          uri: http://www.ckh.com:8701
          predicates:
            - Path=/user/**
        - id: goods-service
          uri: http://www.ckh.com:8602
          predicates:
            - Path=/goods/**, /order/**
        - id: page-service
          uri: http://www.ckh.com:9001
          predicates:
            - Path=/page/**, /assets/**
        - id: admin-service
          uri: http://www.ckh.com:8301
          predicates:
            - Path=/pageContent/**, /admin/**


server:
  port: 80

services:
  versions:
    user:
      v1: 1.0


