spring:
  application:
    name: pawnshop-service-user-provider
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pawnshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: ckh
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
    timeout: 3600s
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    database: 0
    host: 129.211.17.8
    port: 6379
    password:
    pool:
      jedis:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000


server:
  port: 8501

mybatis:
  type-aliases-package: cn.ckh2019.pawnshop.commons.domain
  mapper-locations: classpath:mapper/*.xml

services:
  versions:
    user:
      v1: 1.0

#dubbo

dubbo:
  scan:
    basePackages: cn.ckh2019.pawnshop.service.user.provider.api.impl
  application:
      id: pawnshop-service-user-provider
    name: pawnshop-service-user-provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
    status: server
    serialization: kryo
  registry:
    id: zookeeper
    address: zookeeper://129.211.17.8:2181

management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  health:
    dubbo:
      default: memory
      extras: load,threadpool
