server:
  port: 8401

spring:
  application:
    name: pawnshop-eureka

eureka:
  client:
    register-with-eureka: false # 服务注册,是否将自己注册到Rureka服务中
    fetch-registry: false   #服务发现
    serviceUrl:     # Eureka客户端和 Eureka服务端的交互地址,高可用状态配置对方的地址,单机状态配置自己的地址
      defaultZone: ${EUREKA_SERVER:http://cloud.ckh.com:8401/eureka/}
  server:
    enable-self-preservation: false  #是否开始自我保护模式
    eviction-interval-timer-in-ms: 60000  #服务注册表的清理间隔(默认60*1000)
#  instance:
#    hostname: ${EUREKA_DOMAIN:www.ckh.com}



